print ("Введите ФИО:")
FIO = input()
print("Введите факультет:")
FAC = input()
print("Введите курс:")
COURSE = input()
print("Введите группу:")
GROUP = input()
print("Введите e-mail:")
EMAIL = input()
print("Студент(-ка) ",FIO, "обучается на факультете", FAC, ",на", COURSE, "курсе", "в группе", GROUP, ",e-mail:", EMAIL, end='')